import { generateSEO } from "@/lib/seo";

export const metadata = generateSEO({
  title: "Terms of Service",
  description:
    "HACODE SOLUTIONS Terms of Service. Review the terms and conditions for using our DevSpec catalog and purchasing our specification packs.",
  path: "/terms",
});

export default function TermsPage() {
  return (
    <div className="container mx-auto px-4 py-16 max-w-4xl">
      <h1 className="text-4xl md:text-5xl font-bold mb-6">Terms of Service</h1>
      <p className="text-gray-400 mb-12">Last updated: September 19, 2026</p>

      <div className="prose prose-invert max-w-none">
        <section className="mb-8">
          <h2 className="text-2xl font-bold mb-4">Agreement to Terms</h2>
          <p className="text-gray-300 mb-4">
            By accessing or using the HACODE SOLUTIONS website and services, you
            agree to be bound by these Terms of Service. If you do not agree to
            these terms, please do not use our services.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold mb-4">Use of DevSpecs</h2>
          <h3 className="text-xl font-semibold mb-3">Free DevSpecs</h3>
          <p className="text-gray-300 mb-4">
            Free DevSpecs are provided under the MIT License and can be used
            freely in personal and commercial projects.
          </p>

          <h3 className="text-xl font-semibold mb-3">Premium DevSpecs</h3>
          <p className="text-gray-300 mb-4">
            Premium DevSpecs are sold under a single-user license. You may:
          </p>
          <ul className="list-disc pl-6 text-gray-300 mb-4 space-y-2">
            <li>Use the DevSpec in unlimited personal or commercial projects</li>
            <li>Modify the DevSpec to suit your needs</li>
          </ul>
          <p className="text-gray-300 mb-4">You may not:</p>
          <ul className="list-disc pl-6 text-gray-300 mb-4 space-y-2">
            <li>Redistribute or resell the DevSpec</li>
            <li>Share your purchase with others</li>
            <li>Use the DevSpec to create competing products</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold mb-4">Payments and Refunds</h2>
          <p className="text-gray-300 mb-4">
            All payments are processed securely through Stripe. We offer a 30-day
            money-back guarantee on premium DevSpecs. To request a refund, contact
            support@hacode.solutions within 30 days of purchase.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold mb-4">Intellectual Property</h2>
          <p className="text-gray-300 mb-4">
            All DevSpec content, including documentation, code examples, and
            specifications, is owned by HACODE SOLUTIONS and protected by
            copyright law. Your license grants you specific usage rights as
            outlined above.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold mb-4">Disclaimers</h2>
          <p className="text-gray-300 mb-4">
            DevSpecs are provided "as is" without warranties of any kind. While we
            strive for accuracy and quality, we do not guarantee that DevSpecs
            will be error-free or meet your specific requirements.
          </p>
          <p className="text-gray-300 mb-4">
            You are responsible for testing and validating any code generated by
            AI agents using our DevSpecs before deploying to production.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold mb-4">Limitation of Liability</h2>
          <p className="text-gray-300 mb-4">
            HACODE SOLUTIONS shall not be liable for any indirect, incidental,
            special, or consequential damages arising from your use of our
            DevSpecs or services.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold mb-4">Updates to DevSpecs</h2>
          <p className="text-gray-300 mb-4">
            We may update DevSpecs to reflect new best practices, security
            improvements, or framework updates. Premium DevSpec purchasers receive
            updates for free for the lifetime of the product.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold mb-4">Termination</h2>
          <p className="text-gray-300 mb-4">
            We reserve the right to terminate or suspend access to our services
            for violations of these terms or fraudulent activity.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold mb-4">Changes to Terms</h2>
          <p className="text-gray-300 mb-4">
            We may modify these terms at any time. Continued use of our services
            after changes constitutes acceptance of the new terms.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-bold mb-4">Contact</h2>
          <p className="text-gray-300">
            Questions about these terms? Contact us at{" "}
            <a
              href="mailto:legal@hacode.solutions"
              className="text-brand-purple hover:text-purple-400"
            >
              legal@hacode.solutions
            </a>
          </p>
        </section>
      </div>
    </div>
  );
}
